// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_NL-mYiA5cKzlrefo6yelGBCp3c2mtNM',
    appId: '1:446318752272:web:8705b71954efb0b0279095',
    messagingSenderId: '446318752272',
    projectId: 'training-e65bf',
    authDomain: 'training-e65bf.firebaseapp.com',
    storageBucket: 'training-e65bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOzARNz00V1NZ57bfjTsiLtl-d4mz_itY',
    appId: '1:446318752272:android:ce8dc4e30c4e076d279095',
    messagingSenderId: '446318752272',
    projectId: 'training-e65bf',
    storageBucket: 'training-e65bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCOEn3RxtwsytiEbZIUcEubiVnZUSMaoY',
    appId: '1:446318752272:ios:86e0b96bc0822b24279095',
    messagingSenderId: '446318752272',
    projectId: 'training-e65bf',
    storageBucket: 'training-e65bf.appspot.com',
    iosBundleId: 'com.example.2401Training',
  );
}
